name: gtkhash
adopt-info: gtkhash
version: git
license: GPL-2.0+
grade: stable
base: core20
confinement: strict
compression: lzo

apps:
  gtkhash:
    command: usr/bin/gtkhash
    desktop: usr/share/applications/org.gtkhash.gtkhash.desktop
    common-id: org.gtkhash.gtkhash
    extensions: [ gnome-3-38 ]
    plugs: [ home ]

parts:
  gtkhash:
    source: https://github.com/tristanheaven/gtkhash.git
    plugin: autotools
    build-packages:
      - pkg-config
      - libtool
      - gettext
      - autopoint
      - appstream
      - libglib2.0-dev
      - libgtk-3-dev
      - libgcrypt20-dev
      - libb2-dev
      - librsvg2-bin
      - libxml2-utils
      - at-spi2-core
      - xvfb
      - gnome-icon-theme
    stage-packages:
      - libgtk-3-0
      - libgcrypt20
      - libb2-1
    build-environment:
      - CFLAGS: "${CFLAGS} -O2 -s"
    autotools-configure-parameters:
      - --prefix=/usr # For snap's bindtextdomain() hack
      - --enable-linux-crypto
      - --disable-silent-rules
    override-build: |
      sed -i '/^Icon=/s:=.*:=${SNAP}/meta/gui/gtkhash.svg:' data/org.gtkhash.gtkhash.desktop.in
      snapcraftctl build
      make VERBOSE=1 check || :
      mkdir -vp -- "${SNAPCRAFT_PART_INSTALL}"/meta/gui
      cp -vf -- data/icons/scalable/org.gtkhash.gtkhash.svg "${SNAPCRAFT_PART_INSTALL}"/meta/gui/gtkhash.svg
    parse-info: [ usr/share/metainfo/org.gtkhash.gtkhash.appdata.xml ]
