name: gtkhash
adopt-info: gtkhash
version: git
license: GPL-2.0+
grade: stable
base: core24
confinement: strict

apps:
  gtkhash:
    command: usr/bin/gtkhash
    desktop: usr/share/applications/org.gtkhash.gtkhash.desktop
    common-id: org.gtkhash.gtkhash
    extensions:
      - gnome
    plugs:
      - home
      - removable-media

parts:
  gtkhash:
    source: https://github.com/gtkhash/gtkhash.git
    plugin: meson
    build-packages:
      - libb2-dev
      - libgcrypt20-dev
      - libgtk-3-dev
      - librsvg2-bin
    stage-packages:
      - libb2-1
      - libgcrypt20
      - libgtk-3-0
    meson-parameters:
      - -Dlinux-crypto=true
      - -Dprefix=/usr
      - -Dstrip=true
    override-build: |
      craftctl default
      mkdir -vp -- "${CRAFT_PART_INSTALL}"/meta/gui
      cp -vf -- "${CRAFT_PART_SRC}"/data/icons/scalable/org.gtkhash.gtkhash.svg "${CRAFT_PART_INSTALL}"/meta/gui/gtkhash.svg
    parse-info:
      - usr/share/metainfo/org.gtkhash.gtkhash.appdata.xml
