name: flake

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: nixos-unstable
            build: nix build --print-build-logs
          - name: nixos-26.05
            build: nix build --print-build-logs --override-input nixpkgs github:NixOS/nixpkgs/nixos-26.05
    steps:
      - uses: actions/checkout@v7
      - uses: cachix/install-nix-action@v31
      - run: ${{ matrix.build }}
